---
title: "FinalR"
author: "Elliot Metviner"
date: "12/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


```{r}
census_regions <- read.csv("censusRegions.csv")
state_abb <- read.csv("state_abb_codes.csv")
opioid_death <- read.csv("state_Opioid_Deaths2019.csv")
view(opioid_death)
```

```{r}
opiod_death <- opioid_death %>%
  rename(State = "Location")  ## renamed state to location to allow for easy merge
```

```{r}
merge1 <- merge(opiod_death, state_abb, by.x="State", by.y="State") ## merged data sets by "State"
merge1 <- merge1 %>%
  select("Range.Category", "Age.adjusted.Rate", "Number.of.Deaths", "Code") %>%
  rename(State = "Code")   ## renamed state to code to merge into the next data set

```

```{r}
Opioid_region <- merge(merge1, census_regions, by.x="State", by.y="State") %>%  ## merged data
  select("Age.adjusted.Rate", "Region") %>%   ## selected the two variables for analysis
  group_by(Region) %>%                       ## grouped by region
  summarize(mean_AAR = mean(Age.adjusted.Rate),   ## calculated mean age adjusted rate
            sd_AAR = sd(Age.adjusted.Rate),       ## calculated standard deviation of age adjusted rate
            CoD_AAR = sd_AAR/mean_AAR)            ## 
```





